package TFTP;

public enum ExtendedMenu {
	INVALID_OPCODE,
	EXTRA_DATA_AT_END,
	
	RQ_MISSING_FILENAME,
	RQ_MISSING_FIRST_ZERO,
	RQ_MISSING_MODE,
	RQ_INVALID_MODE,
	RQ_MISSING_SECOND_ZERO,
	
	DATA_OR_ACK_MISSING_BLOCK_NUMBER,
	DATA_OR_ACK_INVALID_BLOCK_NUMBER,
	
	DATA_MISSING_DATA,
	
	ERROR_INVALID_ERROR_CODE,
	ERROR_MISSING_ERROR_CODE,
	ERROR_MISSING_ERROR_MESSAGE,
	ERROR_MISSING_ZERO;
}
